import type { NextConfig } from "next";
const isAzurite = process.env.AZURE_STORAGE_CONNECTION_STRING?.includes('devstoreaccount1') ?? false;

// Minimal, safe-ish Content-Security-Policy. Tweak as needed for external vendors (analytics, fonts, etc.).
const azPublicBase = process.env.AZURE_BLOB_PUBLIC_BASE?.trim();
let azOrigin = "";
try { if (azPublicBase) azOrigin = new URL(azPublicBase).origin; } catch {}
const allowAzurite = isAzurite || (azOrigin.startsWith("http://"));

function buildCsp() {
  const imgSrc = [
    "'self'",
    "data:",
    "blob:",
    "https:",
    // allow Azurite http origins only when running against Azurite
    ...(allowAzurite ? [azOrigin || "http://localhost:10000", "http://azurite-1:10000"] : []),
  ].join(" ");

  const connectSrc = [
    "'self'",
    "https:",
    "wss:",
    "ws:",
    ...(allowAzurite ? [azOrigin || "http://localhost:10000", "http://azurite-1:10000"] : []),
  ].join(" ");

  const styleSrc = "'self' 'unsafe-inline' https://fonts.googleapis.com";
  const fontSrc  = "'self' https://fonts.gstatic.com data:";
  const scriptSrc = "'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://js.stripe.com";
  const frameSrc  = "https://js.stripe.com";

  return [
    "default-src 'self'",
    `img-src ${imgSrc}`,
    `connect-src ${connectSrc}`,
    `style-src ${styleSrc}`,
    `font-src ${fontSrc}`,
    `script-src ${scriptSrc}`,
    `frame-src ${frameSrc}`,
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join("; ");
}
const csp = buildCsp();

const nextConfig: NextConfig = {
  reactStrictMode: true,
  output: "standalone",
  // Remove the X-Powered-By header generated by Next.js
  // (if your Next.js version supports it). We also add global security headers via `headers()`.
  poweredByHeader: false,
  images: {
    unoptimized: isAzurite,
    remotePatterns: [
      // Azurite / local dev
      { protocol: "http", hostname: "localhost",  port: "10000", pathname: "/devstoreaccount1/photos/**" },
      { protocol: "http", hostname: "azurite-1", port: "10000", pathname: "/devstoreaccount1/photos/**" },
      // Azure Blob (production)
      { protocol: "https", hostname: "momentia1.blob.core.windows.net", pathname: "/photos/**" },
      { protocol: "https", hostname: "momentiastorage.blob.core.windows.net", pathname: "/photos/**" },
    ],
  },
  // ← experimental.serverComponentsExternalPackages は使わない
  serverExternalPackages: ["@azure/identity", "@azure/storage-blob", "@prisma/client", "prisma"],

  // Global HTTP headers applied to all routes. Adjust CSP and other values for third-party needs.
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          // HSTS: enable for production (preload option only after you registered at hstspreload.org)
          { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
          // Prevent MIME sniffing
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          // Clickjacking protection
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          // Reasonable Referrer-Policy
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          // Permissions policy (formerly Feature-Policy) — tighten down common features
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()' },
          // Disable legacy XSS filter (modern browsers ignore it; 0 avoids inconsistent behavior)
          { key: 'X-XSS-Protection', value: '0' },
          // Content-Security-Policy — tune for your external assets; this is intentionally conservative
          { key: 'Content-Security-Policy', value: csp },
        ],
      },
    ];
  },
};

export default nextConfig;