name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # --- Debug: Token が Runner に届いているかを確認（中身は出さない）---
      - name: Check SWA token is present
        env:
          TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ Missing AZURE_STATIC_WEB_APPS_API_TOKEN"; exit 1;
          fi
          echo "✅ Token length: ${#TOKEN} chars"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # 念のため明示
          action: "upload"
          # ---- Repository/Build Config ----
          app_location: "/"
          api_location: ""              # Functions は未使用
          output_location: ".next"      # Next.js のビルド出力
          app_build_command: "npm run build"
          skip_api_build: true          # .next を Functions として再ビルドさせない
          # ---- End ----

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"