name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          # ★ここからが修正点
          resourceGroup: momentiav1
          containerAppName: momentiav1 # 'appName' から 'containerAppName' に修正
          acrName: momentiaacr # ACR名を明示的に指定
          imageToBuild: momentiaacr.azurecr.io/momentia:${{ github.sha }} # ビルドとプッシュをこのアクションに任せる
          dockerfilePath: Dockerfile # Dockerfileのパスを指定