name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  RESOURCE_GROUP: momentiav1
  CONTAINER_REGISTRY: momentiaacr
  CONTAINER_APP_NAME: momentiav1

jobs:
  build_and_deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/momentia:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/momentia:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          appName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.CONTAINER_REGISTRY }}.azurecr.io/momentia:${{ github.sha }}